name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build frontend using esbuild
        run: npm install esbuild && ./node_modules/.bin/esbuild ./src/frontend.ts --bundle --outfile=./static/script.js

      - name: Run Javascript Obfuscator
        run: npm install -g javascript-obfuscator && javascript-obfuscator ./static/script.js --output ./static/script.js --config ./obfuscator_config.js

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "esbuild-template" # Change to your project name
          entrypoint: "main.ts"
          root: "."
