name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build using esbuild
        run: npm install esbuild && ./node_modules/.bin/esbuild ./src/frontend.ts --bundle --outfile=./static/script.js

      - name: Run Javascript Obfuscator
        run: npm install javascript-obfuscator && javascript-obfuscator ./static/script.js --output ./static/script.js

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "dirty-dove-43"
          entrypoint: "main.ts"
          root: "."
